
import Head from 'next/head';
import { Navbar } from '../Navbar';

export const MainLayout = ({ children }) => {
    return (
        <>
          <Head>
            <title>About Ivan</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
          <main className="main">
               { children }
          </main>
        </>
      )
}
